apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minecraft-nebulaagent
  namespace: minecraft
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minecraftnebulaagent.vecchia.lol`)
      kind: Rule
      services:
        - name: minecraft-server-nebulaagent
          port: 7458
  tls:
    certResolver: letsencrypt
