---
apiVersion: v1
kind: Secret
metadata:
  name: bluemap-auth
  namespace: minecraft
type: Opaque
stringData:
  # Replace this line with the output of: htpasswd -Bbn <username> <password>
  # Example: admin:$2y$10$XYZ...
  users: |
    map:$2y$05$hOOpR./3hwEpU4E546K7COFSEDbQx1nsvNuzueQuKYAF469mnLcMm
