---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  namespace: minecraft
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce # lo storage locale supporta solo RWO
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - asus
  hostPath:
    path: "/data/k3s_subvolume/minecraft"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  namespace: minecraft
spec:
  storageClassName: local-storage
  volumeName: minecraft-pv
  accessModes:
    - ReadWriteOnce # Deve combaciare con il PV
  resources:
    requests:
      storage: 100Gi
